version: "3.9"

services:

  api:
    build:
      context: .  
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      - MQTT_HOST=mosquitto
      - DATABASE_URL=postgresql+asyncpg://uniparking:uniparking@postgres:5432/uniparking
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      mosquitto:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - uni-parking-net

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - uni-parking-net

  mosquitto:
    image: eclipse-mosquitto:2
    command: ["mosquitto","-c","/mosquitto/config/mosquitto.conf","-v"]
    ports:
      - "1883:1883"
    volumes:
      - type: bind
        source: ./mosquitto-config
        target: /mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - uni-parking-net

  postgres:
    image: postgres:16
    container_name: uniparking-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: uniparking
      POSTGRES_PASSWORD: uniparking
      POSTGRES_DB: uniparking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uniparking -d uniparking"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - uni-parking-net 


volumes:
  redis-data:
  mosquitto-data:
  mosquitto-log:
  pgdata: {}

networks:
  uni-parking-net:
    external: true
