global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'uniparking-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
